name: Aws EKS destroy-cluster
on: 
     workflow_dispatch:
permissions: 
   id-token: write
   contents: read
jobs:
    EC2_Initialize:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
                 
             
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: "${{secrets.AWS_IAM_ROLE}}"
                role-session-name: sampleroesession
                aws-region: "us-east-1"

            - name: version check
              run: terraform version

            - name: Checking plan
              run: terraform plan

            - name: Destroy the infra
              run: terraform destroy -auto-approve
              

              

    